id: PC7754676
initial_creation_type: input
source_metadata:
  title: Mind Training (Lojong)
  language: es
  description: 'Texts on so-called mind training (blo sbyong), the system of practical
    instructions for developing the compassion and wisdom of bodhicitta:'
  volume:
    7c59d1fb69cc48f691b40badfa705f98:
      title: Seven Points of Training the Mind According to the Great Vehicle
      parent: Seven Points of Mind Training
    49585ca2e4584bed99b18304154c214c:
      title: Commentary on the Seven Points
      parent: Seven Points of Mind Training
    1bdac12aca45416b802fb6e25beb3c3d:
      title: Notes on the Seven Points of Mind Training
      parent: Seven Points of Mind Training
    5e1856e9ea64471e8398ec3b4c5c6b1d:
      title: Ambrosia for the Mind
      parent: Seven Points of Mind Training
    cf5415b1d86043c68fbec05856fad92c:
      title: Eight Verses of Training the Mind
      parent: Eight Verses of Training the Mind
    eb3d69b25d8545629ad8137e93c8c833:
      title: The Thirty-Seven Practices of All the Bodhisattvas
      parent: Thirty-Seven Practices
    2c5a5e5c5f924a63a7ea00aa0d0649f7:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Aspiration Prayers
    4a6acbee2b24465d9eef8c1e6fb5c1de:
      title: 'The Excellent Path to Enlightenment: An Aspiration Towards the Mahāyāna
        Mind Training'
      parent: Aspiration Prayers
    d16fee8c117245cd9480444f9620dbab:
      title: 'The Finest Jewel: An Aspiration Prayer of Mahāyāna Mind Training'
      parent: Aspiration Prayers
    a34f01b3aaa9450ca7bddcf44e5ce5ec:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    c286a52566104833b4eb2f27007879da:
      title: The Bodhisattva’s Garland of Jewels
      parent: Lojong (general)
    4a3eb204cb2d470fb17c2f630e2ee0a3:
      title: Turning Suffering & Happiness Into Enlightenment
      parent: Lojong (general)
    55a693f676c04af3b97e40fa909951b1:
      title: The Sayings of Geshe Langri Tangpa
      parent: Lojong (general)
    b2e2cf3e3f294c98bee28b931bd9dae8:
      title: How to Transform Sickness and Other Circumstances
      parent: Lojong (general)
    d11f6eddf94d4464b8929790d7fa6f15:
      title: Thirty Pieces of Heart Advice
      parent: Lojong (general)
    7273d142620c4075a35283471699b5cb:
      title: Three Principal Aspects of the Path
      parent: Lojong (general)
created_at: '2022-03-01T04:44:49.389684'
last_modified_at: '2022-03-01T04:44:49.389687'
